<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sold Players - {{ $league->name }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 10px;
            line-height: 1.4;
            color: #333;
            padding: 20px;
        }
        
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #4F46E5;
        }
        
        .header h1 {
            font-size: 18px;
            color: #1E293B;
            margin-bottom: 5px;
        }
        
        .header p {
            font-size: 11px;
            color: #64748B;
        }
        
        .stats {
            text-align: center;
            margin-bottom: 15px;
            padding: 8px;
            background: #F1F5F9;
            border-radius: 4px;
        }
        
        .stats p {
            font-size: 10px;
            font-weight: 600;
            color: #475569;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }
        
        thead {
            background: #4F46E5;
            color: white;
        }
        
        th {
            padding: 8px 6px;
            text-align: left;
            font-size: 9px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        
        td {
            padding: 6px;
            border-bottom: 1px solid #E2E8F0;
            font-size: 9px;
        }
        
        tr:nth-child(even) {
            background: #F8FAFC;
        }
        
        .sl-number {
            font-weight: 700;
            color: #1E293B;
            text-align: center;
            width: 30px;
        }
        
        .player-name {
            font-weight: 600;
            color: #1E293B;
        }
        
        .amount {
            font-weight: 700;
            color: #059669;
            text-align: right;
        }
        
        .footer {
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #E2E8F0;
            text-align: center;
            font-size: 8px;
            color: #94A3B8;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $league->name }}</h1>
        <p>Sold Players List - Generated on {{ now()->format('F d, Y h:i A') }}</p>
    </div>
    
    <div class="stats">
        <p>Total Sold Players: {{ $soldPlayers->count() }}</p>
    </div>
    
    <table>
        <thead>
            <tr>
                <th class="sl-number">SL</th>
                <th>Player</th>
                <th>Role</th>
                <th>Team</th>
                <th style="text-align: right;">Amount</th>
                <th>Time</th>
            </tr>
        </thead>
        <tbody>
            @forelse($soldPlayers as $index => $leaguePlayer)
            <tr>
                <td class="sl-number">{{ $index + 1 }}</td>
                <td class="player-name">{{ $leaguePlayer->player->name ?? 'Unknown' }}</td>
                <td>{{ $leaguePlayer->player->primaryGameRole->gamePosition->name ?? $leaguePlayer->player->position->name ?? 'N/A' }}</td>
                <td>{{ $leaguePlayer->leagueTeam->team->name ?? 'Unknown' }}</td>
                <td class="amount">₹{{ number_format($leaguePlayer->bid_price ?? 0) }}</td>
                <td>{{ $leaguePlayer->updated_at->format('M d, h:i A') }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="6" style="text-align: center; padding: 20px; color: #94A3B8;">No players sold yet</td>
            </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="footer">
        <p>Generated by {{ config('app.name') }} • {{ now()->format('F d, Y h:i A') }}</p>
    </div>
</body>
</html>
